# Generated by Django 6.0.7 on 2026-09-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills, e.g. Python, Django, SQL (optional)'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills (optional)'),
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semantic_skill_score', models.FloatField(default=0.0)),
                ('skill_coverage', models.FloatField(default=0.0)),
                ('tfidf_similarity', models.FloatField(default=0.0)),
                ('experience_match', models.FloatField(default=0.0)),
                ('education_encoded', models.FloatField(default=0.0)),
                ('certification_present', models.FloatField(default=0.0)),
                ('rf_prediction', models.FloatField(blank=True, help_text='RandomForest predicted probability of shortlist', null=True)),
                ('xgb_prediction', models.FloatField(blank=True, help_text='XGBoost predicted probability of shortlist', null=True)),
                ('final_score', models.FloatField(blank=True, help_text='Score used for ranking candidates', null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.jobposting')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='jobs.resume')),
            ],
            options={
                'ordering': ['-final_score'],
                'unique_together': {('resume', 'job')},
            },
        ),
    ]
